title: Fredrik Möller
description: >-
  Personal site, resume, and blog.
baseurl: ""
url: "https://fredrikmoller1324.github.io"

theme: minima

header_pages:
  - blog.md
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
